make:
	g++ -g -std=c++11 -pthread *.cpp -o client -lsfml-graphics -lsfml-window -lsfml-audio -lsfml-network -lsfml-system

makewin:
	g++ -g -std=c++11 -pthread *.cpp -o client -lsfml-graphics -lsfml-window -lsfml-audio -lsfml-network -lsfml-system

clean:
	rm *~ ./client

cleanwin:
	rm *~ ./client.exe
