make:
	g++ -g -std=c++11 -pthread *.cpp -o client -lsfml-graphics -lsfml-window -lsfml-audio -lsfml-network -lsfml-system

makewin:
	g++ -g -std=c++11 -pthread main.cpp -o client -lsfml-graphics -lsfml-window -lsfml-audio -lsfml-network -lsfml-system

test:
	g++ -g -std=c++11 -pthread test.cpp -o test -lsfml-graphics -lsfml-window -lsfml-audio -lsfml-network -lsfml-system

clean:
	rm *~ ./client

cleanwin:
	rm *~ ./client.exe
